// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// table_1d_fast
IntegerVector table_1d_fast(IntegerVector input, int n);
RcppExport SEXP gibbsLda_table_1d_fast(SEXP inputSEXP, SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type input(inputSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        IntegerVector __result = table_1d_fast(input, n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// table_2d_fast
IntegerMatrix table_2d_fast(IntegerVector lhs, IntegerVector rhs, int n_lhs, int n_rhs);
RcppExport SEXP gibbsLda_table_2d_fast(SEXP lhsSEXP, SEXP rhsSEXP, SEXP n_lhsSEXP, SEXP n_rhsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type lhs(lhsSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type rhs(rhsSEXP );
        Rcpp::traits::input_parameter< int >::type n_lhs(n_lhsSEXP );
        Rcpp::traits::input_parameter< int >::type n_rhs(n_rhsSEXP );
        IntegerMatrix __result = table_2d_fast(lhs, rhs, n_lhs, n_rhs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gibbs_lda_c
IntegerVector gibbs_lda_c(IntegerMatrix docs, IntegerMatrix Ndk, IntegerMatrix Nwk, IntegerVector Nk, IntegerVector Z, size_t K, int niter = 20, double beta = .05, double alpha = .01);
RcppExport SEXP gibbsLda_gibbs_lda_c(SEXP docsSEXP, SEXP NdkSEXP, SEXP NwkSEXP, SEXP NkSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP niterSEXP, SEXP betaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerMatrix >::type docs(docsSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type Ndk(NdkSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type Nwk(NwkSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type Nk(NkSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type Z(ZSEXP );
        Rcpp::traits::input_parameter< size_t >::type K(KSEXP );
        Rcpp::traits::input_parameter< int >::type niter(niterSEXP );
        Rcpp::traits::input_parameter< double >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP );
        IntegerVector __result = gibbs_lda_c(docs, Ndk, Nwk, Nk, Z, K, niter, beta, alpha);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP gibbsLda_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
