# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

table_1d_fast <- function(input, n) {
    .Call('gibbsLda_table_1d_fast', PACKAGE = 'gibbsLda', input, n)
}

table_2d_fast <- function(lhs, rhs, n_lhs, n_rhs) {
    .Call('gibbsLda_table_2d_fast', PACKAGE = 'gibbsLda', lhs, rhs, n_lhs, n_rhs)
}

gibbs_lda_c <- function(docs, Ndk, Nwk, Nk, Z, K, niter = 20L, beta = .05, alpha = .01) {
    .Call('gibbsLda_gibbs_lda_c', PACKAGE = 'gibbsLda', docs, Ndk, Nwk, Nk, Z, K, niter, beta, alpha)
}

rcpp_hello_world <- function() {
    .Call('gibbsLda_rcpp_hello_world', PACKAGE = 'gibbsLda')
}

